# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "8e454aa4-f2a2-4668-ab1e-db55fd44e671"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "a5df33d2bb6d6b7c733d092908fb089ba217f5f8",
    build_secret: "0c1702b4bc2c42afe1315b0010bc9b565a4b816c4cec4fa3025bd8e52e9e8a86"
  )
end
